language: go

go:
  - 1.11.x
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - go mod download

script:
  - PROTOBUF_VERSION=3.3.0
  - PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
  - pushd /home/travis
  - wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
  - unzip ${PROTOC_FILENAME}
  - bin/protoc --version
  - popd
  - make proto
  - make test
